name: docstagram_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_chat_ui: ^1.6.14
  file_picker: ^8.0.0+1
  flutter_chat_types: ^3.6.2
  image_picker: ^1.1.2
  uuid: ^4.4.2
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  intl: ^0.19.0
  http: ^1.2.2
  mime: ^1.0.5
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.32.0
  web_socket_channel: ^3.0.1
  permission_handler: ^11.3.1
  firebase_messaging: ^14.9.4
  hive: ^2.2.3
  pointycastle: ^3.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/messages.json
