// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcau07axhersFdJUAqKht_RQAdBck8qEI',
    appId: '1:569255552041:web:f528f4b7e7cae22622a838',
    messagingSenderId: '569255552041',
    projectId: 'docstagram-notif',
    authDomain: 'docstagram-notif.firebaseapp.com',
    storageBucket: 'docstagram-notif.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3O7lJFR3oxpThYHkVnixP8tNUQnyWGEs',
    appId: '1:569255552041:android:609a3e55d2f459f622a838',
    messagingSenderId: '569255552041',
    projectId: 'docstagram-notif',
    storageBucket: 'docstagram-notif.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQO_iDf8WEb1mzas3VW16J5JnE3nAiMeo',
    appId: '1:569255552041:ios:1f35e451a02d46ab22a838',
    messagingSenderId: '569255552041',
    projectId: 'docstagram-notif',
    storageBucket: 'docstagram-notif.appspot.com',
    iosBundleId: 'com.example.docstagramChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQO_iDf8WEb1mzas3VW16J5JnE3nAiMeo',
    appId: '1:569255552041:ios:1f35e451a02d46ab22a838',
    messagingSenderId: '569255552041',
    projectId: 'docstagram-notif',
    storageBucket: 'docstagram-notif.appspot.com',
    iosBundleId: 'com.example.docstagramChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcau07axhersFdJUAqKht_RQAdBck8qEI',
    appId: '1:569255552041:web:c30328e892e4787222a838',
    messagingSenderId: '569255552041',
    projectId: 'docstagram-notif',
    authDomain: 'docstagram-notif.firebaseapp.com',
    storageBucket: 'docstagram-notif.appspot.com',
  );
}
